const dataText = {
    "en": {
        global_enter: "enter",
        global_back: "Back",
        global_select: "Enter",
        global_ok: "OK",
        global_games: "Games",
        global_no_games: "No Games",
        global_all: "All",
        global_title: "Title",
        global_menu: "Menu",
        global_view: "View",
        global_noFavorites: "No favorites set",
        global_favorite: "Favorites",
        home_system: "system",
        home_collection: "collection",
        home_favorite: "favorite",
        home_recent: "recent",
        games_play: "Start",
        games_info: "Details",
        games_select: "Select",
        games_favorite: "Add to favorite",
        games_favorite_cancel: "Remove from favorite",
        games_more: "More",
        sort_by: "By ",
        sort_title: "By Title",
        sort_last_played: "By Last Played",
        sort_rating: "By Rating",
        sort_release_year: "By Release Year",
        sort_show_all: "Show All",
        sort_favorites_only: "Favorites Only",
        sort_play_time: "By Play Time",
        sort_play_count: "By Play Count",
        meta_released: "Released in: ",
        meta_players: "Number of players: ",
        meta_play_count: "Play Count: ",
        meta_play_time: "Play Time: "
    },
    "cn": {
        global_enter: "进入",
        global_back: "返回",
        global_select: "确定",
        global_games: "游戏",
        global_no_games: "无游戏",
        global_all: "全部",
        global_title: "标题",
        global_menu: "菜单",
        global_view: "视图",
        global_favorite: "收藏",
        home_system: "平台",
        home_collection: "合集",
        home_favorite: "收藏",
        home_recent: "最近",
        games_play: "开始",
        games_info: "详情",
        games_select: "选择",
        games_favorite: "添加收藏",
        games_favorite_cancel: "取消收藏",
        games_more: "更多",
        sort_by: "按",
        sort_title: "按标题",
        sort_last_played: "按最后游玩",
        sort_rating: "按评分",
        sort_release_year: "按发售时间",
        sort_show_all: "显示全部",
        sort_favorites_only: "仅显示收藏",
        sort_play_time: "按游玩时长",
        sort_play_count: "按游玩次数",
        meta_released: "发售日期: ",
        meta_players: "游戏人数: ",
        meta_play_count: "游玩次数: ",
        meta_play_time: "游玩时长: "
    }
}

const theme = {
    "background": "#333",
    "text": "#70000000",
    "title": "#444",
    "background_dark": "#222",
    "text_dark": "#DDD",
    "title_dark": "#DDD",
    "background_grid": "#222",
    "gridLargeColumnCount": 3,
    "primaryColor": "#1565C0",
    "systemColumns" : 6,
    "collectionColumns" : 5,
    "gamelistColumns": 6,
    "maxRecentlyPlayed": 30
}
